### ISSUE TITLE
Does not seem to work on Gedit 3.20.1

### ISSUE THREAD

**Issue by benmoran56** [isamert/gedi#1]
First of all, thanks for making this.
Unfortunately It doesn't seem to do anything on my machine. I am running Arch, which recently updated to Gedit 3.20.1.

I installed and enabled the Gedi plugin. I then made a new document and set the highlighting mode to Python 3.  If I start Gedit from the command line I can see a "Gedi is activated" message, but there no code completion popups appear. 

Is this not supported yet for Gedit 3.20.1, or is there some additional troubleshooting I can do? 
Thanks!

**Comment by benmoran56** [comment]
Oops! It was because the newly created file did not have a *.py  extension. I took a look through your code, and it was pretty obvious what the issue was. 

Sorry for the false alarm!

**Comment by isamert** [comment]
I should also check for the mime type of the file probably, that can be better.
