### ISSUE TITLE
How trigger completion

### ISSUE THREAD

**Issue by bagustris** [isamert/gedi#6]
I already install the plugin along with its requirements. It seems OK but nothing happens.
Just curious, is there any shortcut (Ctrl/tab/etc+) needed to trigger the completion...?

**Comment by isamert** [comment]
It should automatically complete. Did you activate the plugin from `Preferences -> Plugins` menu? Are you editing a file that has `.py` extension? Start gedit in a terminal and see if there are any outputs: `gedit file.py`.

**Comment by bagustris** [comment]
Sorry, it works now after restart. In another machine, I forget to install jedi via pip3. Thanks!
I used Ubuntu 16.04.

**Comment by CsatiZoltan** [comment]
I have jedi installed with `pip3 install jedi`, Gedi is activated, the file extension is .py, but still no autocompletion.

```bash
$ gedit filename.py
Gedi is activated.
```
Then I start typing Python code. No autocompletion, no message in the terminal. When I quit:

```bash
Gedi is deactivated.
```

**Comment by sentinel3** [comment]
I encounter same issue as @CsatiZoltan reported.  I am running Ubuntu 20.04.
- installed jedi via `pip3`
- `git` the files
- open the `gedit test.py` from terminal, enable plugin
- same `Gedi is activated`, `Gedi is deactivated`. 
- no auto completion as I type a few lines.
